export const addItemForm = [
  {
    value: "",
    handleInputChange: null,
    type: "text",
    className: "form-control",
    id: "floatingInput",
    placeholder: "name@example.com",
    label: "Enter title",
    fieldName: "title",
  },
  {
    value: "",
    handleInputChange: null,
    type: "text",
    className: "form-control",
    id: "floatingInput",
    placeholder: "your first name",
    label: "Enter description ",
    fieldName: "description",
  },
];

export const registrationFormColumns = [
  {
    value: "",
    onChangeEvent: null,
    type: "text",
    className: "form-control",
    id: "floatingInput",
    placeholder: "name@example.com",
    label: "enter your e-mail",
  },
  {
    value: "",
    onChangeEvent: null,
    type: "text",
    className: "form-control",
    id: "floatingInput",
    placeholder: "your first name",
    label: "your first name",
  },
  {
    value: "",
    onChangeEvent: null,
    type: "text",
    className: "form-control",
    id: "floatingInput",
    placeholder: "your last name",
    label: "your last name",
  },
  {
    onChangeEvent: null,
    value: "",
    type: "password",
    className: "form-control",
    id: "floatingPassword",
    placeholder: "Password",
    label: "Password",
  },
];
